---
- name: Install bind9
  hosts: dns
  become: yes
  tasks:
  - name: Update
    apt:
      update_cache: yes

  - name: Install bind9
    apt:
      name: bind9, bind9utils
      state: present

  - name: timestamp
    ansible.builtin.shell:
      cmd: date +%s&
    register: timestamp
    run_once: true

  - name: Generation zones
    ansible.builtin.template:
      src: templates/labzone.j2
      dest: /etc/bind/db.local
      owner: bind
      group: bind
  
  - name: Modifs named.conf.local
    ansible.builtin.blockinfile:
      path: /etc/bind/named.conf.local
      block: |
        zone "lab.lan" {
          type master;
          file "/etc/bind/db.local";
        };

  - name: Reload bind9
    ansible.builtin.service:
      name: bind9
      state: restarted

- name: Configuration DNS
  hosts: all
  become: yes
  tasks:
  - name: Import tâche
    ansible.builtin.import_tasks:
      file: tasks/set_dns.yml


- name: Load balancer
  hosts: lb
  become: yes
  tasks:
  - name: Update
    apt:
      update_cache: yes
  - name: Install apache2
    apt:
      name: apache2
      state: present
  - name: Boucle installation modules apache2
    community.general.apache2_module:
      name: "{{ item.name }}"
      state: present
    loop:
      - { name: 'proxy_http'}
      - { name: 'proxy_http2'}
      - { name: 'proxy_balancer'}
      - { name: 'lbmethod_byrequests'}
  - name: Generation confs
    ansible.builtin.template:
      src: templates/lb-apache-conf.j2
      dest: /etc/apache2/sites-available/000-default.conf
      owner: www-data
      group: www-data
    register: state

  - name: Reload apache2
    ansible.builtin.service:
      name: apache2
      state: restarted
    when: state["changed"] == true

- name: Serveurs WEB
  hosts: web
  become: yes
  tasks:
  - name: Update
    apt:
      update_cache: yes
  - name: Install php & apache2
    apt:
      name: apache2, php
      state: present
  - name: Remove file
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent
  - name: cp file
    ansible.builtin.template:
      src: files/index.php
      dest: /var/www/html/index.php
      owner: www-data
      group: www-data
